### ISSUE TITLE
🐛 Bug Report: Table of contents don't match the content

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/website#982] opened 2024-05-23 21:42 UTC
### 👟 Reproduction steps

1. Browse to https://appwrite.io/terms
2. Click on Termination in the Table of contents on the left

### 👍 Expected behavior

The Table of contents scrolls to Termination

### 👎 Actual Behavior

It scrolls to Governing Law:

<img width="1255" alt="image" src="https://github.com/appwrite/website/assets/1477010/186ac0b4-5297-46a4-be67-1565b55d9ca7">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kabhamo** [comment] 2024-05-23 23:02
Hi @stnguyen90,
I believe I can help fix this bug, can you assign me this issue, please?

**Comment by cbum-dev** [comment] 2024-05-28 08:51
@stnguyen90 Can I take this up?

**Comment by stnguyen90** [comment] 2024-05-28 22:04
@kabhamo, assigned to you. Thanks for your interest! 🙏🏼 Please keep us updated on your progress or I'll need to reassign the issue.

**Comment by cbum-dev** [comment] 2024-06-03 14:38
Is this issue still open?
@stnguyen90

**Comment by stnguyen90** [comment] 2024-06-04 00:45
@cbum-dev, I've assigned this to @kabhamo, but if there's no activity after a week or so, I can reassign it to you.

**Comment by rogix** [comment] 2024-06-11 19:35
Hi @stnguyen90,

I noticed that this issue has been open for a while. Has it been reassigned to someone? If not, I’d be happy to work on it.

Thanks!

**Comment by kabhamo** [comment] 2024-06-14 20:24
I believe in less than 2 days will be a pull request for the bug.
If I need help I will notify you

**Comment by stnguyen90** [comment] 2024-06-18 00:28
@rogix, assigned to you! Let me know if you're not able to work on this and I'll unassign you.

**Comment by rogix** [comment] 2024-06-19 19:45
Hi, @stnguyen90,

I was looking into this issue and realized that it’s not actually a bug but part of the expected behavior of the Melt-UI library.

In the code:
https://github.com/appwrite/website/blob/377131b3e5975730a7155dd9a8baca048d802eaa/src/lib/components/TocRoot.svelte#L26-L27

The `lowest` option means that the heading of the lowest visible content is considered active. That’s why when the user clicks on the `Termination` item, the `Governing Law` heading is activated, as it is the lowest one visible on the screen.

One suggestion would be to use a different option, such as `highest` instead of `lowest`. This would make the highest item active. However, it also has its issues. The ToC component considers the content, not just the `title`, to decide which menu item should be active. You can check their documentation here: https://melt-ui.com/docs/builders/table-of-contents#accessible-by-design.

Here’s what happens when we choose the `highest` option:

![image](https://github.com/appwrite/website/assets/12768403/fd29c2dd-1265-41e2-9f21-8af42fed4ac5)

The *Introduction* menu is active, but the title is hidden at the top. This option is active because the *content* of the heading is visible. These defaults make it challenging to get it "right."

Another alternative is the `all` option. With this, every menu item whose header or content is displayed will be active:

![image](https://github.com/appwrite/website/assets/12768403/99777f7d-694d-4dee-9359-68dd5a000a87)

Alternatively, we could ignore the `active` part of the ToC component and create a custom one to make it work the way we intend.

Please let me know if you prefer any of these alternatives or if you have other suggestions.

**Comment by stnguyen90** [comment] 2024-06-20 04:43
@rogix, thanks for the detailed analysis! Let me bring this back to the team! 🙏🏼

**Comment by rogix** [comment] 2024-06-20 11:49
Sure!

**Comment by stnguyen90** [comment] 2024-06-21 00:12
@rogix, Would you please create a PR with `activeType` as `highest` and `scrollOffset` as `0`. Then, the team can play around with it and see how to proceed.

**Comment by rogix** [comment] 2024-06-21 13:09
Of course! I can to that.

**Comment by rogix** [comment] 2024-06-24 23:56
Hi, @stnguyen90!

Sorry for the delay. I’ve created the PR following your suggestions. Let me know if it works.

**Closed as completed** 2024-06-25 20:22 UTC
Labels: bug, help wanted
