### ISSUE TITLE
🐛 Bug Report: No Navigation In Docs Page

### ISSUE THREAD

**Issue by ArnabBCA** [appwrite/website#174] opened 2023-10-03 04:58 UTC
### 👟 Reproduction steps

1. Go to appwrite Docs page
There is no navigation to other pages in the navbar. Only Docs Page is visible.
If no Navigation is present the user has to press back button in the browser which ruins user experience.

### 👍 Expected behavior

There should be navigation to other pages in the navbar.
The final navigation should contain Docs, Community, Blog, Pricing.
![No navigation](https://github.com/appwrite/website/assets/113178195/f365ead2-8960-4ba6-b47d-05bc97ffe2b3)

### 👎 Actual Behavior

there is no navigation to other pages other than the Docs itself.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ArnabBCA** [comment] 2023-10-03 04:59
I would like to work on this issue

**Comment by stnguyen90** [comment] 2023-10-03 13:26
@ArnabBCA, thanks for raising this issue! Since it's Hacktoberfest, we'll be focusing on Hacktoberfest issues for the moment.

**Comment by shivanshu814** [comment] 2023-10-04 05:32
can you assign me this issue @stnguyen90

**Comment by ArnabBCA** [comment] 2023-10-04 05:34
> can you assign me this issue @stnguyen90 

Bro I have already worked on it kindly look for another issue

**Comment by ArnabBCA** [comment] 2023-10-04 05:35
> > can you assign me this issue @stnguyen90 
> 
> Bro I have already worked on it kindly look for another issue

It is first come first serve

**Comment by shaurya-jain23** [comment] 2023-10-13 23:50
Can you please assign it to me

**Comment by gewenyu99** [comment] 2023-10-20 21:02
We don't plan on adding these pages. The docs are like this by design, and we plan on skipping these navigation buttons. I'll leave the issue open, but know that we don't plan on implementing this :)

**Comment by stnguyen90** [comment] 2024-05-31 00:31
Closing as we don't plan on changing the navigation.

**Closed by stnguyen90** 2024-05-31 00:31 UTC
Labels: bug
